### ISSUE TITLE
I have a question~

### ISSUE THREAD

**Issue by xl-0909** [hamido/opencore-efi-asus-z390-h#1]
Can I use it？
I don't have a discrete graphics card，just UHD630。
finally，How do i use it？
Thanks！！

**Comment by hamido** [comment]
I believe you can. 

To install this `EFI`head over to [releases page](https://github.com/hamido/opencore-efi-asus-z390-h/releases) and download the latest EFI. Then unzip it in the efi partition.

If you get stuck, refer to opencore documentation:
https://dortania.github.io/OpenCore-Desktop-Guide/

**Comment by xl-0909** [comment]
I use it，but I got stuck `please go to https://panic.apple.com...`
My U disk is usb3.0,and mac os is 10.15.5
How can i solve this problem?
Thanks！！

**Comment by hamido** [comment]
Try removing `agdpmod=pikera` from `boot-args` that might fix the problem.

**Comment by xl-0909** [comment]
Thank you very much.
I have successfully installed the mac os system by modifying some configurations.
But I cannot use my microphone. 
How can I solve this problem?

**Comment by hamido** [comment]
You may need to change input selection. Navigate to System Preferences -> Sound -> Input (tab) and try the listed options.

<img width="780" alt="image" src="https://user-images.githubusercontent.com/5708741/85276043-e0027c80-b489-11ea-9ad4-814d8a4222e2.png">

**Comment by xl-0909** [comment]
I tried this method, but it didn't work, I can hear the sound output, just can't use the microphone
![image](https://user-images.githubusercontent.com/30011762/85277659-5321e800-b4b6-11ea-8627-8cc040d8a3a8.png)

**Comment by hamido** [comment]
Hmm, this does not make sense 🤔 

Since we share the same motherboard, you shouldn't be making any other configurations to get the mic working, because I did not. At this point I have three guesses:

1. If this is a newly built PC, the mic may not be connected to motherboard.
2. Something is wrong with the mic. If you could test it with another pc we would know for sure.
3. Changing `alcid` might work. I am using value `1` and the mic works, in theory it should work for you too

**Comment by xl-0909** [comment]
Thank you very much for answering my question, maybe I need this adapter.
![image](https://user-images.githubusercontent.com/30011762/85355445-3382d200-b53f-11ea-9e03-39fbe3598ffb.png)

**Comment by hamido** [comment]
It is worth a try. The splitter shouldn't cost much.

**Comment by xl-0909** [comment]
The microphone problem has been solved。
I used a sapphire rx590 8G graphics card, but the system ran very slowly within a few minutes after it was turned on,After about 5 minutes, the system is operating normally.
Why is this happening?

**Comment by hamido** [comment]
The documentation does not mention any additional configurations for that card:

- https://dortania.github.io/GPU-Buyers-Guide/modern-gpus/amd-gpu.html

Can you describe the slowness? Is it graphical (acceleration), launching the applications or something else?

**Comment by xl-0909** [comment]
thanks!
