### ISSUE TITLE
I have a question~

### ISSUE THREAD

**Issue by xl-0909** [hamido/opencore-efi-asus-z390-h#2]
I downloaded the latest version and installed Mac OS Big Sur, but my USB 3.0 port does not work, just USB2.0 port work
。
How should i make them work？
thanks！
![image](https://user-images.githubusercontent.com/30011762/99881617-c0989700-2c55-11eb-844b-7c6b1acc8b5c.png)

**Comment by hamido** [comment]
I have not yet upgraded to Big Sur.
For the problem you could try [usb mapping](https://dortania.github.io/OpenCore-Post-Install/usb/#macos-and-the-15-port-limit). 
I plan to replace `USBInjectAll.kext` with a proper mapping in the future, too.

**Comment by xl-0909** [comment]
I fix it！
Maybe it's a problem with the USBInjectAll version.or it's because I open `XhciPortLimit`.
I will try replace USBInjectAll.kext with a proper mapping tonight.
Thanks!
